name: Linting

on:
  push:
    branches: [ CI/GitHubAction ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint TS
        run: npm run lint
      - name: Lint SASS
        run: npm run lint:scss
      - name: Lint commit
        run: npm run lint:commitlint
      - name: Build
      - run: npm run build
      - run: npm test
